<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/02_pandas/01_series_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas Series

one-dimentional labeled array -- any data type

Array --- in horizontal
Series -- vertical

Creating series

In [1]:
import numpy as np
import pandas as pd

In [8]:
lables = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array(my_list)
d = {'p':10, 'q':20, 'r':30}

In [3]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=lables)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(d)

p    10
q    20
r    30
dtype: int64