<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/02_pandas/02_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

Creating a Dataframe

In [17]:
Data = {
    'Name':['Hitesh','Om','Ajay','Kunal'],
    'Age':[22,32,21,23],
    'City':['Kolhapur','Pune','Mumbai','Nagpur'],
    'Salary':[60000,52000,41000,63000],
}
df = pd.DataFrame(Data)

In [18]:
df

     Name  Age      City  Salary
0  Hitesh   22  Kolhapur   60000
1      Om   32      Pune   52000
2    Ajay   21    Mumbai   41000
3   Kunal   23    Nagpur   63000

In [8]:
data_list = [
    ['Hitesh',22,'Kolhapur',60000],
    ['Om',32,'pune',52000],
    ['Ajay',22,'Munmbai',41000],
    ['Kunal',23,'Nagpur',63000]
    ]
df2 = pd.DataFrame(data_list)

In [9]:
df2

        0   1         2      3
0  Hitesh  22  Kolhapur  60000
1      Om  32      pune  52000
2    Ajay  22   Munmbai  41000
3   Kunal  23    Nagpur  63000

In [11]:
coulmns_names=['Name','Age','City','Salary']
df3=pd.DataFrame(data_list,columns=coulmns_names)
df3

     Name  Age      City  Salary
0  Hitesh   22  Kolhapur   60000
1      Om   32      pune   52000
2    Ajay   22   Munmbai   41000
3   Kunal   23    Nagpur   63000

Selection and indexing of columns

In [12]:
df3['Name']

0    Hitesh
1        Om
2      Ajay
3     Kunal
Name: Name, dtype: object

In [19]:
df[['Name','City']]

     Name      City
0  Hitesh  Kolhapur
1      Om      Pune
2    Ajay    Mumbai
3   Kunal    Nagpur

Creating a new column

In [29]:
# need to provide the list and number of elements should match the no. of rows
df['PRN'] = ['2004','2005','2001','2010']

In [30]:
df

     Name  Age      City  Salary   PRN
0  Hitesh   22  Kolhapur   60000  2004
1      Om   32      Pune   52000  2005
2    Ajay   21    Mumbai   41000  2001
3   Kunal   23    Nagpur   63000  2010

In [31]:
# axis 0 --> x-asix , it work left to right
# axis 1 --> y-asix , it work top to bottom
# no axis given --> default axis = 0
# so axis 0 mean - it will chack in first column ,here 0,1,2..
# and axis 1 mean-it will chack in first row -Name Age City Salary PRN
df.drop('PRN',axis=1)

     Name  Age      City  Salary
0  Hitesh   22  Kolhapur   60000
1      Om   32      Pune   52000
2    Ajay   21    Mumbai   41000
3   Kunal   23    Nagpur   63000

In [32]:
# but PRN column is not permantly removed
df

     Name  Age      City  Salary   PRN
0  Hitesh   22  Kolhapur   60000  2004
1      Om   32      Pune   52000  2005
2    Ajay   21    Mumbai   41000  2001
3   Kunal   23    Nagpur   63000  2010

In [33]:
df.drop('PRN',axis=1, inplace = True)

In [34]:
# use inplace = True to remove it completly , previously it was
# only showing snapshot of it
df

     Name  Age      City  Salary
0  Hitesh   22  Kolhapur   60000
1      Om   32      Pune   52000
2    Ajay   21    Mumbai   41000
3   Kunal   23    Nagpur   63000

In [36]:
# removing row
df.drop(2,axis=0,inplace = True)

In [37]:
df

     Name  Age      City  Salary
0  Hitesh   22  Kolhapur   60000
1      Om   32      Pune   52000
3   Kunal   23    Nagpur   63000

Selecting Rows

In [38]:
df.loc[0]

Name        Hitesh
Age             22
City      Kolhapur
Salary       60000
Name: 0, dtype: object

In [41]:
df.loc[[0,3]]

     Name  Age      City  Salary
0  Hitesh   22  Kolhapur   60000
3   Kunal   23    Nagpur   63000

Selecting Subsets of rows and columns

In [42]:
df.loc[[0,1]][['Name','City']]

     Name      City
0  Hitesh  Kolhapur
1      Om      Pune

Conditional Selection

In [43]:
df3

     Name  Age      City  Salary
0  Hitesh   22  Kolhapur   60000
1      Om   32      pune   52000
2    Ajay   22   Munmbai   41000
3   Kunal   23    Nagpur   63000

In [44]:
# age > 20 and salary > 50000
df3[(df3['Age']>20) & (df3['Salary']>50000)]

     Name  Age      City  Salary
0  Hitesh   22  Kolhapur   60000
1      Om   32      pune   52000
3   Kunal   23    Nagpur   63000