<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/02_pandas/03_missingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

Finding Missing Data

In [2]:
data = {
    'Name':['Hitesh','Om','Ajay','Kunal'],
    'Age':[22,np.nan,21,23],
    'City':['Kolhapur','Pune','Mumbai','Nagpur'],
    'Salary':[np.nan,52000,np.nan,63000],
}
df = pd.DataFrame(data)

In [3]:
df

     Name   Age      City   Salary
0  Hitesh  22.0  Kolhapur      NaN
1      Om   NaN      Pune  52000.0
2    Ajay  21.0    Mumbai      NaN
3   Kunal  23.0    Nagpur  63000.0

In [4]:
df.isna()

    Name    Age   City  Salary
0  False  False  False    True
1  False   True  False   False
2  False  False  False    True
3  False  False  False   False

In [5]:
df.isna().sum()

Name      0
Age       1
City      0
Salary    2
dtype: int64

In [6]:
df.isna().any()

Name      False
Age        True
City      False
Salary     True
dtype: bool

Removing Missing Data

In [7]:
df

     Name   Age      City   Salary
0  Hitesh  22.0  Kolhapur      NaN
1      Om   NaN      Pune  52000.0
2    Ajay  21.0    Mumbai      NaN
3   Kunal  23.0    Nagpur  63000.0

In [8]:
df.dropna()

    Name   Age    City   Salary
3  Kunal  23.0  Nagpur  63000.0

In [9]:
df

     Name   Age      City   Salary
0  Hitesh  22.0  Kolhapur      NaN
1      Om   NaN      Pune  52000.0
2    Ajay  21.0    Mumbai      NaN
3   Kunal  23.0    Nagpur  63000.0

In [11]:
# thresh =4  -->  mean your row should have at leat 4 non-null values in them
df.dropna(thresh=4)

    Name   Age    City   Salary
3  Kunal  23.0  Nagpur  63000.0

Inplace = True --> for really applying these functions

In [12]:
df.fillna(0)

     Name   Age      City   Salary
0  Hitesh  22.0  Kolhapur      0.0
1      Om   0.0      Pune  52000.0
2    Ajay  21.0    Mumbai      0.0
3   Kunal  23.0    Nagpur  63000.0

In [13]:
columns_to_fill = ['Age', 'Salary']
df[columns_to_fill] = df[columns_to_fill].fillna(df[columns_to_fill].mean())

In [14]:
df

     Name   Age      City   Salary
0  Hitesh  22.0  Kolhapur  57500.0
1      Om  22.0      Pune  52000.0
2    Ajay  21.0    Mumbai  57500.0
3   Kunal  23.0    Nagpur  63000.0

dropna - row wise .
selection - column wise.
fillna - column wise .

In [15]:
data2 = {
    'Name':['Hitesh','Om','Ajay','Kunal'],
    'Age':[22,np.nan,21,np.nan],
    'City':['Kolhapur','Pune','Mumbai','Nagpur'],
    'Salary':[np.nan,52000,np.nan,63000],
}
df2 = pd.DataFrame(data2)

In [16]:
df2

     Name   Age      City   Salary
0  Hitesh  22.0  Kolhapur      NaN
1      Om   NaN      Pune  52000.0
2    Ajay  21.0    Mumbai      NaN
3   Kunal   NaN    Nagpur  63000.0

In [19]:
values = {'Age': 20,'Salary':50000 }
df2.fillna(value=values)

     Name   Age      City   Salary
0  Hitesh  22.0  Kolhapur  50000.0
1      Om  20.0      Pune  52000.0
2    Ajay  21.0    Mumbai  50000.0
3   Kunal  20.0    Nagpur  63000.0