<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/02_pandas/04_mergingJoiningConcatination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

Merging 2 dataframe

In [5]:
employees= pd.DataFrame({
    'employee_id': [1, 2, 3, 4],
    'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
    'department': ['Accounting', 'Engineering', 'Engineering', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 4,6],
    'salary': [70000, 80000, 120000, 90000],
    'bonus': [10000, 20000, 30000, 40000]
})

In [6]:
employees

   employee_id  name   department
0            1   Bob   Accounting
1            2  Jake  Engineering
2            3  Lisa  Engineering
3            4   Sue           HR

In [7]:
salaries

   employee_id  salary  bonus
0            1   70000  10000
1            2   80000  20000
2            4  120000  30000
3            6   90000  40000

In [9]:
pd.merge(employees, salaries, on='employee_id',how='inner')

   employee_id  name   department  salary  bonus
0            1   Bob   Accounting   70000  10000
1            2  Jake  Engineering   80000  20000
2            4   Sue           HR  120000  30000

In [10]:
pd.merge(employees, salaries, on='employee_id',how='outer')

   employee_id  name   department    salary    bonus
0            1   Bob   Accounting   70000.0  10000.0
1            2  Jake  Engineering   80000.0  20000.0
2            3  Lisa  Engineering       NaN      NaN
3            4   Sue           HR  120000.0  30000.0
4            6   NaN          NaN   90000.0  40000.0

In [11]:
pd.merge(employees, salaries, on='employee_id',how='right')

   employee_id  name   department  salary  bonus
0            1   Bob   Accounting   70000  10000
1            2  Jake  Engineering   80000  20000
2            4   Sue           HR  120000  30000
3            6   NaN          NaN   90000  40000

In [12]:
pd.merge(employees, salaries, on='employee_id',how='left')

   employee_id  name   department    salary    bonus
0            1   Bob   Accounting   70000.0  10000.0
1            2  Jake  Engineering   80000.0  20000.0
2            3  Lisa  Engineering       NaN      NaN
3            4   Sue           HR  120000.0  30000.0

In [8]:
pd.merge(employees, salaries, left_on='employee_id', right_on='employee_id')

   employee_id  name   department  salary  bonus
0            1   Bob   Accounting   70000  10000
1            2  Jake  Engineering   80000  20000
2            4   Sue           HR  120000  30000

Concatinatino of 2 dataframes

In [15]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
})
df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5'],
    'D': ['D3', 'D4', 'D5']
})

In [16]:
# column based
pd.concat([df1, df2])

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
0  A3  B3  C3  D3
1  A4  B4  C4  D4
2  A5  B5  C5  D5

In [17]:
# row based
pd.concat([df1, df2],axis=1)

    A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A3  B3  C3  D3
1  A1  B1  C1  D1  A4  B4  C4  D4
2  A2  B2  C2  D2  A5  B5  C5  D5

Joining 2 data frames

In [18]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
},index=['K0', 'K1', 'K2'])
df2 = pd.DataFrame({
    'C': ['C0', 'C2', 'C3'],
    'D': ['D0', 'D2', 'D3'],
},index=['K0', 'K2', 'K3'])

In [19]:
df1.join(df2)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [20]:
df1.join(df2,how = 'outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [21]:
df2.join(df1,how = 'outer')

      C    D    A    B
K0   C0   D0   A0   B0
K1  NaN  NaN   A1   B1
K2   C2   D2   A2   B2
K3   C3   D3  NaN  NaN