<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/02_pandas/05_GroupByAggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B','A', 'B'],
    'store': ['X', 'X', 'Y', 'Y', 'X', 'Y', 'X', 'Y'],
    'Sales': [100, 150, 200, 250, 300, 350,200, 250,],
    'Qantity': [10, 15, 20, 25, 30, 35,20, 25,],
    'Date': pd.date_range(start='2023-01-01', periods=8, freq='D')
}
df= pd.DataFrame(data)

In [3]:
df

  Category store  Sales  Qantity       Date
0        A     X    100       10 2023-01-01
1        B     X    150       15 2023-01-02
2        A     Y    200       20 2023-01-03
3        B     Y    250       25 2023-01-04
4        A     X    300       30 2023-01-05
5        B     Y    350       35 2023-01-06
6        A     X    200       20 2023-01-07
7        B     Y    250       25 2023-01-08

In [ ]:
# group by category and calculate the sum of sales

In [5]:
df.groupby('Category')

In [6]:
cat = df.groupby('Category')
for category, group in cat:
    print(f"Category: {category}")
    print(group)
    print()

Category: A
  Category store  Sales  Qantity       Date
0        A     X    100       10 2023-01-01
2        A     Y    200       20 2023-01-03
4        A     X    300       30 2023-01-05
6        A     X    200       20 2023-01-07

Category: B
  Category store  Sales  Qantity       Date
1        B     X    150       15 2023-01-02
3        B     Y    250       25 2023-01-04
5        B     Y    350       35 2023-01-06
7        B     Y    250       25 2023-01-08

In [7]:
df.groupby('Category')['Sales'].sum()

Category
A     800
B    1000
Name: Sales, dtype: int64

In [10]:
# group by multiple column
# group by category and stores

In [9]:
df.groupby(['Category','store'])['Sales'].sum()

Category  store
A         X        600
          Y        200
B         X        150
          Y        850
Name: Sales, dtype: int64

Aggregation

In [11]:
# mean median mode min max count std

In [12]:
df['Sales'].mean()

np.float64(225.0)

In [13]:
df['Sales'].agg(['mean','median','min','max','std','count'])

mean      225.000000
median    225.000000
min       100.000000
max       350.000000
std        80.178373
count       8.000000
Name: Sales, dtype: float64