<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/02_pandas/08_FeatureExtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df =pd.read_csv('anime.csv')

In [4]:
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [5]:
# need to extract episode numbers from title
# to create new column for episode count

In [6]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [7]:
def extract_episodes(txt):
  check = False
  data = ""
  for i in txt:
    if i == ")":
      check = False
      return data
    if check == True:
      data += i
    if i == "(":
      check = True

In [8]:
df['Episodes'] = df["Title"].apply(extract_episodes)

In [9]:
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [10]:
# Episodes --> numeric
# first remove eps word
df['Episodes'] = df['Episodes'].str.replace(" eps","")

In [11]:
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [12]:
type(df.loc[0]['Episodes'])

str

In [13]:
# str to num
df['Episodes'] = df['Episodes'].astype(int)

In [14]:
type(df.loc[0]['Episodes'])

numpy.int64

In [15]:
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

Make a new column fro time stamp

In [16]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [17]:
def extract_time(txt):
  check = False
  data = ""
  for i in range(len(txt)):
    if txt[i] == ')':
      for j in range(i+1,i+20):
        data += txt[j]
      return data

In [18]:
df['Title'].apply(extract_time)

0     Apr 2009 - Jul 2010
1     Apr 2011 - Sep 2011
2     Oct 2022 - Dec 2022
3     Apr 2015 - Mar 2016
4     Apr 2019 - Jul 2019
5     Apr 2011 - Mar 2012
6     Jan 2021 - Jan 2021
7     Oct 2011 - Sep 2014
8     Apr 2022 - Jun 2022
9     Oct 2012 - Mar 2013
10    Mar 2023 - May 2023
11    Jan 1988 - Mar 1997
12    Jul 2023 - Aug 2023
13    Apr 2021 - Jun 2021
14    Jan 2017 - Mar 2017
15    Apr 2006 - Mar 2010
16    Sep 2016 - Sep 2016
17    Oct 2017 - Mar 2018
18    Oct 2008 - Mar 2009
19    Apr 2008 - Sep 2008
20    Jul 2013 - Jul 2013
21    Sep 2020 - Sep 2020
22    Aug 2017 - Aug 2017
23    Jul 2018 - Oct 2018
24    Apr 2004 - Sep 2005
25    Aug 2016 - Aug 2016
26    Dec 2022 - Dec 2022
27    Oct 2022 - Dec 2022
28    Dec 2022 - Dec 2022
29    Jan 2023 - Jun 2023
30    Jul 2023 - Aug 2023
31    Jan 2018 - Mar 2018
32    Apr 2020 - Oct 2021
33    Jan 2019 - Apr 2019
34    Dec 2020 - Mar 2021
35    Dec 2021 - Feb 2022
36    Jan 2017 - Jan 2017
37    Apr 2023 - Jun 2023
38    Oct 2016 - Dec 2016
39    Jul 2001 - Jul 2001
40    Jul 2013 - Dec 2013
41    Jan 2022 - Apr 2022
42    Oct 2000 - Mar 2002
43    Apr 1998 - Apr 1999
44    Apr 2022 - Oct 2022
45    Jul 2019 - Dec 2019
46    Oct 2014 - Dec 2014
47    Jan 2017 - Mar 2017
48    Oct 2022 - Dec 2022
49    Feb 1999 - Sep 1999
Name: Title, dtype: object

In [19]:
df['Total Time'] = df['Title'].apply(extract_time)

In [20]:
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [21]:
# let's extract total numner of months from total time

In [22]:
def calculate_months(period):
    start, end = period.split(' - ')
    start = pd.to_datetime(start, format='%b %Y')
    end = pd.to_datetime(end, format='%b %Y')

    months = (end.year - start.year) * 12 + (end.month - start.month)
    return months + 1   # +1 to include both start and end month

df['Months'] = df['Total Time'].apply(calculate_months)

In [23]:
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [24]:
# which anime has highest episode count

In [26]:
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [27]:
# animes with top 5 episode count

In [28]:
# which is the longest running anime